name: glitch_text
description: Glitch Text - A Flutter package for creating Text widget with glitch effects & added support of  8+ glitch fonts
version: 0.0.2
homepage: https://github.com/Dinoy-Raj/glitch_text

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  google_fonts: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: hacked
      fonts:
        - asset: assets/fonts/hacked.ttf

    - family: debug
      fonts:
        - asset: assets/fonts/debug.otf

    - family: bugfast
      fonts:
        - asset: assets/fonts/bugfast.ttf

    - family: daughterglitch
      fonts:
        - asset: assets/fonts/daughterglitch.ttf

    - family: glitchbold
      fonts:
        - asset: assets/fonts/glitchbold.ttf

    - family: glitchinside
      fonts:
        - asset: assets/fonts/glitchinside.otf

    - family: songlitch
      fonts:
        - asset: assets/fonts/songlitch.ttf

    - family: thoseglitch
      fonts:
        - asset: assets/fonts/thoseglitch.otf
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
